name: my first action

on: 
  push:
     branches:
     - master

jobs:
  deployment:
       runs-on: ubuntu-latest
       steps:
       - name: checkout
         uses: action/checkout@v1
       
       - name: SSH into server and deploy
         uses: appleboy/ssh-action@v0.1.4
         with:
          host: 192.168.100.161             # Replace with your server IP
          username: root                # Replace with the server username, typically 'root'
          password: 123     # Replace with your root password
          script: |
            echo "Deploying application..."
            cd /var/www/html/
            systemctl restart apache2
            

