name: my first action

on: 
  push:
     branches:
     - master

jobs:
  deployment:
       runs-on: ubuntu-latest
       steps:
       - name: checkout
         uses: action/checkout@v1
       
       - name: Configure AWS credentials
         uses: aws-action/configure-aws-credential@v1
         with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
       -name: deploy static site to S3 bucket
        run: aws s3 sync . s3://tws-github-action-demo --delete

